tmp_dir: /tmp/shrimp
server:
  debug: true
  hostname: onze-desktop.local
  port: 6000
  websocket:
    enable_logging: false
    enable_engine_logging: false
  subprocess_polling_period_ms: 250
videofeed_out:
  port: 6001
  streaming_binary: ffmpeg
commander:
  command_reset_delay_ms: 250
engines:
  propulsion:
    # enable, phase
    gpios: [6, 12]
#  rotation:
#    gpios: []
#  vtrans:
#    gpios: []
commands:
  forward:
    auto_reset: true
    actions:
      - name: propulse
        engine: propulsion
        callback: forward
        speed: 1
  backward:
    auto_reset: true
    actions:
      - name: retropulse
        engine: propulsion
        callback: backward
        speed: 1
