tmp_dir: /tmp/shrimpstation
server:
  debug: false
  hostname: shrimpstation.local
  port: 5000
  videofeed_port: 5001
  websocket:
    enable_logging: false
    enable_engine_logging: false
  subprocess_polling_period_ms: 1000
shrimp:
  hostname: 10.0.0.2 #shrimp.local
  web_api_port: 6000
